"""
Economics tracking: token costs, value produced, profit calculation.

Every action is tracked for ROI. This is the financial heartbeat of the system.
"""

from dataclasses import dataclass, field
from typing import Dict, List, Any, Optional
from datetime import datetime
from enum import Enum


class CostCategory(str, Enum):
    WORKER_EXECUTION = "worker_execution"
    AI_DECISION_MAKING = "ai_decision_making"
    MONITORING = "monitoring"
    INVESTIGATION = "investigation"
    INFRASTRUCTURE = "infrastructure"


class ValueCategory(str, Enum):
    COMPLETED_TASK = "completed_task"
    CLIENT_PAYMENT = "client_payment"
    COST_SAVINGS = "cost_savings"
    DATA_VALUE = "data_value"


@dataclass
class ResourceCost:
    """Cost of a resource (tokens, compute, etc.)."""

    category: CostCategory
    amount: float  # token count or equivalent
    related_id: Optional[str] = None  # task_id, worker_id, etc.
    timestamp: datetime = field(default_factory=datetime.now)
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class ValueProduced:
    """Value generated by the system."""

    category: ValueCategory
    amount: float  # monetary value or equivalent
    related_id: Optional[str] = None  # task_id, client_id, etc.
    timestamp: datetime = field(default_factory=datetime.now)
    metadata: Dict[str, Any] = field(default_factory=dict)


class EconomicsTracker:
    """
    Tracks all costs and value produced.

    Answers questions like:
    - Total tokens spent this session?
    - ROI of each task?
    - Profitability by worker?
    - Which opportunities are worth pursuing?
    """

    def __init__(self):
        self.costs: List[ResourceCost] = []
        self.value: List[ValueProduced] = []

    def record_cost(
        self,
        category: CostCategory,
        amount: float,
        related_id: Optional[str] = None,
        metadata: Optional[Dict[str, Any]] = None,
    ) -> None:
        """Record a cost."""
        cost = ResourceCost(
            category=category,
            amount=amount,
            related_id=related_id,
            metadata=metadata or {},
        )
        self.costs.append(cost)

    def record_value(
        self,
        category: ValueCategory,
        amount: float,
        related_id: Optional[str] = None,
        metadata: Optional[Dict[str, Any]] = None,
    ) -> None:
        """Record value produced."""
        value = ValueProduced(
            category=category,
            amount=amount,
            related_id=related_id,
            metadata=metadata or {},
        )
        self.value.append(value)

    def total_cost(self, category: Optional[CostCategory] = None) -> float:
        """Total costs, optionally filtered by category."""
        if category is None:
            return sum(c.amount for c in self.costs)
        return sum(c.amount for c in self.costs if c.category == category)

    def total_value(self, category: Optional[ValueCategory] = None) -> float:
        """Total value, optionally filtered by category."""
        if category is None:
            return sum(v.amount for v in self.value)
        return sum(v.amount for v in self.value if v.category == category)

    def net_profit(self) -> float:
        """Total profit (value - cost)."""
        return self.total_value() - self.total_cost()

    def roi(self) -> float:
        """Return on investment (profit / cost)."""
        total_cost = self.total_cost()
        if total_cost == 0:
            return 0.0
        return self.net_profit() / total_cost

    def cost_by_category(self) -> Dict[str, float]:
        """Breakdown of costs by category."""
        result = {}
        for cost in self.costs:
            result[cost.category.value] = result.get(cost.category.value, 0) + cost.amount
        return result

    def value_by_category(self) -> Dict[str, float]:
        """Breakdown of value by category."""
        result = {}
        for v in self.value:
            result[v.category.value] = result.get(v.category.value, 0) + v.amount
        return result

    def profitability_by_worker(self) -> Dict[str, Dict[str, float]]:
        """
        Calculate profitability for each worker.

        Returns: {worker_id: {total_value, total_cost, profit, roi}}
        """
        result = {}

        # Aggregate by worker
        for cost in self.costs:
            if cost.related_id:
                if cost.related_id not in result:
                    result[cost.related_id] = {"total_cost": 0, "total_value": 0}
                result[cost.related_id]["total_cost"] += cost.amount

        for val in self.value:
            if val.related_id:
                if val.related_id not in result:
                    result[val.related_id] = {"total_cost": 0, "total_value": 0}
                result[val.related_id]["total_value"] += val.amount

        # Calculate profit and ROI
        for worker_id, data in result.items():
            profit = data["total_value"] - data["total_cost"]
            roi = (
                profit / data["total_cost"] if data["total_cost"] > 0 else 0
            )
            data["profit"] = profit
            data["roi"] = roi

        return result

    def get_summary(self) -> Dict[str, Any]:
        """Get economic summary."""
        return {
            "total_cost": self.total_cost(),
            "total_value": self.total_value(),
            "net_profit": self.net_profit(),
            "roi_percent": self.roi() * 100,
            "cost_breakdown": self.cost_by_category(),
            "value_breakdown": self.value_by_category(),
        }
